# copied from https://github.com/solana-developers/github-workflows/blob/main/.github/workflows/test.yaml

name: Test Program with artifact upload

on:
  workflow_dispatch:
    inputs:
      program:
        description: "Program to test"
        required: true
        default: "hello_solana"

jobs:
  install_pnpm:
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

  test:
    uses: borisnieuwenhuis/github-workflows/.github/workflows/test.yaml@v1.0.0
    with:
      program: hello_solana
      testresults: junit.xml

  process-results:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: ./junit.xml
